version: "3.9"

services:
  llmexp_chatbot:
    image: llmexp_chatbot_image:$VERSION
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llmexp_chatbot_app
    ports:
      - "8000:8000"
    volumes:
      - llmexp_chatbot_data:/app/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  llmexp_chatbot_data:
    name: llmexp_chatbot_data
